# Generated by Django 5.0 on 2023-12-20 12:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("main_color", models.CharField(max_length=255)),
                ("secondary_color", models.CharField(max_length=255)),
                ("brand", models.CharField(max_length=255)),
                (
                    "catalog_inclusion_date",
                    models.DateField(default=django.utils.timezone.now),
                ),
                ("picture_url", models.URLField()),
                (
                    "price_per_unit",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("initial_stock", models.IntegerField()),
                ("current_stock", models.IntegerField()),
                ("description", models.TextField(blank=True, editable=False)),
                ("is_active", models.BooleanField(default=True)),
                ("deactivated_at", models.DateTimeField(blank=True, null=True)),
                ("logo_color", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "Cap",
                "verbose_name_plural": "Caps",
                "db_table": "cap",
            },
        ),
        migrations.CreateModel(
            name="Material",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "Material",
                "verbose_name_plural": "Materials",
                "db_table": "material",
            },
        ),
        migrations.CreateModel(
            name="Shirt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("main_color", models.CharField(max_length=255)),
                ("secondary_color", models.CharField(max_length=255)),
                ("brand", models.CharField(max_length=255)),
                (
                    "catalog_inclusion_date",
                    models.DateField(default=django.utils.timezone.now),
                ),
                ("picture_url", models.URLField()),
                (
                    "price_per_unit",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("initial_stock", models.IntegerField()),
                ("current_stock", models.IntegerField()),
                ("description", models.TextField(blank=True, editable=False)),
                ("is_active", models.BooleanField(default=True)),
                ("deactivated_at", models.DateTimeField(blank=True, null=True)),
                ("size", models.CharField(max_length=255)),
                (
                    "size_type",
                    models.CharField(
                        choices=[
                            ("man", "MAN"),
                            ("woman", "WOMAN"),
                            ("unisex", "UNISEX"),
                        ],
                        max_length=255,
                    ),
                ),
                ("sleeves", models.BooleanField()),
            ],
            options={
                "verbose_name": "Shirt",
                "verbose_name_plural": "Shirts",
                "db_table": "shirt",
            },
        ),
        migrations.CreateModel(
            name="ShirtMaterialComposition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("percentage", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="product.material",
                    ),
                ),
                (
                    "shirt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="product.shirt"
                    ),
                ),
            ],
            options={
                "verbose_name": "Shirt Material Composition",
                "verbose_name_plural": "Shirt Material Compositions",
                "db_table": "shirt_material_composition",
            },
        ),
        migrations.AddField(
            model_name="shirt",
            name="materials",
            field=models.ManyToManyField(
                through="product.ShirtMaterialComposition", to="product.material"
            ),
        ),
    ]
